title: "Dosk 技术站"
tagline: "SpringHack 的无名技术小站"
description: "SpringHack 的无名技术小站"
baseurl: "/"
url: "https://dosk.win"

github_username: springhack
twitter_username: springhack

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

markdown: kramdown
kramdown:
  input: GFM
lsi: false
quiet: false
paginate: 10
paginate_path: "page:num"
highlighter: rouge
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-github-metadata
  - rouge
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-mentions

header_pages:
  - pages/archives.md
  - pages/categories.md
  - pages/previous.md
  - pages/about.md

font-size: small

comments_provider: gitalk
gitalk:
  clientID: '63125e6057f210f8095c'
  clientSecret: 'e0a6c16cb45c54eb578e6fead8a87cf70b0471e0'
  repo: 'springhack'
  owner: 'springhack'
