title: "Dosk 技术站"
tagline: "SpringHack 的无名技术小站"
description: "SpringHack 的无名技术小站"
github_username: springhack
baseurl: "/"
url: "https://dosk.win"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

markdown: kramdown
kramdown:
    input: GFM
lsi: false
quiet: false
paginate: 10
paginate_path: "page:num"
highlighter: rouge
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-github-metadata
  - rouge
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-mentions

header_pages:
  - pages/404.md
  - pages/about.md
  - pages/archives.md
  - pages/categories.md
  - pages/old_posts.md

# set the size of the text to 'large' or 'small', default is small
font-size: small

gitalk:
  clientID: '63125e6057f210f8095c'
  clientSecret: 'e0a6c16cb45c54eb578e6fead8a87cf70b0471e0'
  repo: 'SpringHack'
  owner: 'springhack'
