collections:
  - name: blog
    label: Blogs
    create: true
    folder: _posts
    slug: '{{year}}-{{month}}-{{day}}-{{filename}}'
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: post
      - label: Filename
        name: filename
        widget: filename
      - label: Title
        name: title
        widget: string
      - label: Categories
        name: categories
        widget: select
        multiple: true
        default: ['code']
        options: ['code','life','work','game']
      - label: Description
        name: description
        widget: string
      - label: Keywords
        name: keywords
        widget: string
        required: false
      - label: Body
        name: body
        widget: markdown
  - name: page
    label: Pages
    create: true
    folder: pages
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: categories
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Keywords
        name: keywords
        widget: string
        required: false
      - label: Comments
        name: comments
        widget: boolean
        required: false
      - label: Menu
        name: menu
        widget: string
        required: false
      - label: Permalink
        name: permalink
        widget: string
      - label: Body
        name: body
        widget: markdown

backend:
  name: github
  branch: main
  repo: springhack/springhack

slug:
  encoding: unicode
  clean_accents: false

media_folder: uploads

show_preview_links: false

site_url: https://www.dosk.win

# logo_url: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48Zz48dGl0bGU+YmFja2dyb3VuZDwvdGl0bGU+PHJlY3QgZmlsbD0iIzAwMDAwMDAwIiBpZD0iY2FudmFzX2JhY2tncm91bmQiIGhlaWdodD0iMTAyIiB3aWR0aD0iMzAyIiB5PSItMSIgeD0iLTEiLz48L2c+PGc+PHRleHQgZmlsbD0iIzAwMDAwMCIgc3Ryb2tlLXdpZHRoPSIwIiB4PSIyNS45NjUyMiIgeT0iNDUuNDUzMTMiIGlkPSJzdmdfMSIgZm9udC1zaXplPSIyNCIgZm9udC1mYW1pbHk9IidmYW50YXN5Jywgc2VyaWYiIHRleHQtYW5jaG9yPSJzdGFydCIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSIgdHJhbnNmb3JtPSJtYXRyaXgoMi4xNDk1MDA3NzgyNzA1Nzg0LDAsMCwxLjk0NTQ1NDU5NzQ3MzE0NDMsLTMwLjEyNTc0MzMwODk1ODIyLC0yMi4xNzM4NjQ4NTYzNjIzNDMpICIgc3Ryb2tlPSIjMDAwIj5TcHJpbmdIYWNrPC90ZXh0PjwvZz48L3N2Zz4='
